# Copyright (C) 2020 Michael Picht
#
# This file is part of smsync (Smart Music Sync).
#
# smsync is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# smsync is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with smsync. If not, see <http://www.gnu.org/licenses/>.

image: archlinux:latest

stages: 
    - deploy

deploy_smsync-git:
    stage: deploy
    only:
        changes:
            - pkg/PKGBUILD
        refs:
            - master

    before_script:
        # update arch linux and install additional packages  
        - pacman -Syu --noconfirm base base-devel git openssh    
        # set up ssh for access to web space
        - eval $(ssh-agent -s)
        - echo "$AUR_SSH_KEY" | tr -d '\r' | ssh-add -
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - echo "$AUR_HOST_INFO" > ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts
        # set git config
        - git config --global user.email "$GITLAB_USER_EMAIL"
        - git config --global user.name "$GITLAB_USER_NAME"

    script:
        - git clone ssh://${AUR_USER}@${AUR_URL}/smsync-git.git build
        - chgrp nobody build
        - chmod g+ws build
        - setfacl -m u::rwx,g::rwx build
        - setfacl -d --set u::rwx,g::rwx,o::- build          
        - cp pkg/PKGBUILD build
        - cd build  
        - sudo -u nobody makepkg --printsrcinfo > .SRCINFO
        - git add PKGBUILD .SRCINFO
        - git commit -m "${CI_COMMIT_MESSAGE}"
        - git push  
